# Generated by Django 3.2.9 on 2021-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_type_assessment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_type',
            name='assessment_name',
            field=models.CharField(choices=[('Monthly Test - 1', 'Monthly Test - 1'), ('Monthly Test - 2', 'Monthly Test - 2'), ('Midterm Exam', 'Midterm Exam'), ('Monthly Test - 3', 'Monthly Test - 3'), ('Monthly Test - 4', 'Monthly Test - 4'), ('Final Exam', 'Final Exam')], max_length=255),
        ),
    ]
