# Generated by Django 3.2.9 on 2021-12-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('assessments', '0004_auto_20211215_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='class_name',
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.class_list'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('assessment_type', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessment_type',
            unique_together={('session_year', 'assessment_name')},
        ),
    ]
