# Generated by Django 3.2.9 on 2021-12-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_blood_group'),
        ('assessments', '0009_alter_result_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='Assessment',
            new_name='assessment',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('assessment', 'student')},
        ),
    ]
