# Generated by Django 4.0 on 2021-12-31 18:21

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_auto_20211221_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(validators=[assessments.models.Assessment.validate_date]),
        ),
    ]
