# Generated by Django 3.2.9 on 2021-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_blood_group'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher_allocation',
            unique_together={('session_year', 'class_name', 'teacher')},
        ),
    ]
