# Generated by Django 3.2.9 on 2021-12-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teacher_allocation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher_allocation',
            unique_together={('session_year', 'class_name')},
        ),
    ]
