# Generated by Django 4.0 on 2021-12-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_blood_group'),
        ('home', '0003_alter_teacher_allocation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_list',
            name='class_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
