# Generated by Django 4.0 on 2022-01-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staff'),
        ('home', '0005_alter_teacher_allocation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_list',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_name',)},
        ),
    ]
