# Generated by Django 4.0 on 2022-01-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staff'),
        ('home', '0006_alter_class_list_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class_list',
            unique_together={('session_year', 'class_name', 'class_section', 'class_teacher')},
        ),
    ]
