# Generated by Django 3.2.9 on 2021-12-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0003_alter_student_current_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_class', to='home.class_list'),
        ),
        migrations.AlterField(
            model_name='student',
            name='started_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_class', to='home.class_list'),
        ),
    ]
