# Generated by Django 3.2.9 on 2021-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211208_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
