# Generated by Django 3.2.9 on 2021-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
    ]
