# Generated by Django 3.2.9 on 2021-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211208_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
