# Generated by Django 4.0 on 2022-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teacher_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
