# Generated by Django 4.0 on 2022-01-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_class_list_unique_together'),
        ('accounts', '0011_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='started_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_class', to='home.class_list'),
        ),
    ]
