# Generated by Django 4.0 on 2022-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_started_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='started_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
